services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=portfolio
      - POSTGRES_PASSWORD=devpass
      - POSTGRES_DB=portfolio_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:          # yalnızca yerel geliştirme için aç
      - "5432:5432"

  backend:
    build: ./backend
    env_file: ./.env
    depends_on:
      - postgres
    ports:
      - "3001:3000"
    command: sh -c "npx prisma generate && npx prisma migrate deploy && node src/server.js"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  pgdata: